Repository Octomiro/gosap, pull requests merged in 2024-12, with the labels that each got.

#6 feat: retrieve PurchaseOrder documents
  README.md
  config.go
  gosap.go
  gosap_test.go
  testdata/TestGetDeliveryNotes.golden
  testdata/TestGetItems.golden
  testdata/TestGetPurchaseOrders.golden
  types.go
Labels: enhancement, feature

#11 Feat: Add Inventory counting line number and description
  testdata/TestGetInventoryCountings.golden
  testdata/TestGetItems.golden
  types.go
Labels: enhancement

#13 fix: remove omitempty tag for `BaseLine`
  types.go
Labels: bug

#14 Add omitempty to inventory counting type
  types.go
Labels: enhancement
